#!/bin/sh
#
# This is started by
#       cegcc-update-website-startup
# and its output is saved in a file.
#
# Variables NIGHTLY_DIR and WEB_DIR are received from the other script.
#
cd $NIGHTLY_DIR/website
svn update
cd $NIGHTLY_DIR/docs
svn update
#
# Run the update_news script
#
export NIGHTLY_DIR WEB_DIR HOME_DIR
#
sh $NIGHTLY_DIR/scripts/update_news.sh
#
cp $NIGHTLY_DIR/website/* $WEB_DIR
cp $NIGHTLY_DIR/website/images/* $WEB_DIR/images
cp $NIGHTLY_DIR/docs/* $WEB_DIR/docs
exit 0
