#!/bin/sh
HOME_DIR=/home/groups/c/ce/cegcc
TMP_DIR=$HOME_DIR/tmp
NIGHTLY_DIR=$HOME_DIR/nightly-dir
WEB_DIR=$HOME_DIR/htdocs
OUTPUT=out.`date +%y%m%d.%H%M`

export NIGHTLY_DIR WEB_DIR

#
# Phase one - update the script that does the real work.
#
cd $NIGHTLY_DIR/scripts
date >$TMP_DIR/$OUTPUT 2>&1
svn update >>$TMP_DIR/$OUTPUT 2>&1
#
# Phase two - run it.
#
cd $HOME_DIR
sh -x $NIGHTLY_DIR/scripts/cegcc-update-website
# sh $NIGHTLY_DIR/scripts/cegcc-update-website >>$TMP_DIR/$OUTPUT 2>&1

#
# This is the old version - harder to maintain.
#
# $HOME_DIR/cegcc-update-website >$TMP_DIR/$OUTPUT 2>&1

#
# Before terminating, clean up old logging.
#
find $TMP_DIR -type f -ctime +7 -exec rm -f {} \;
#
# Terminate cleanly
#
exit 0
