ARCH=arm
SCRIPT_NAME=pe

OUTPUT_FORMAT="pei-arm-wince-little"
LITTLE_OUTPUT_FORMAT="pei-arm-wince-little"
BIG_OUTPUT_FORMAT="pei-arm-wince-big"

RELOCATEABLE_OUTPUT_FORMAT="pe-arm-wince-little"

TEMPLATE_NAME=pe
ENTRY="WinMainCRTStartup"
SUBSYSTEM=PE_DEF_SUBSYSTEM
TARGET_UNDERSCORE=\"\"
TARGET_PAGE_SIZE=0x1000
