//#define MSNET_IMPORT(ENUM, STR) ENUM

MSNET_IMPORT(OS_WSACLEANUP, "WSACleanup"),
MSNET_IMPORT(OS_WSAIOCTL, "WSAIoctl"),
MSNET_IMPORT(OS_WSASTARTUP, "WSAStartup"),
MSNET_IMPORT(OS_WSAFDISSET, "__WSAFDIsSet"),

MSNET_IMPORT(OS_ACCEPT, "accept"),
MSNET_IMPORT(OS_BIND, "bind"),
MSNET_IMPORT(OS_CLOSESOCKET, "closesocket"),
MSNET_IMPORT(OS_CONNECT, "connect"),
MSNET_IMPORT(OS_GETHOSTBYADDR, "gethostbyaddr"),
MSNET_IMPORT(OS_GETHOSTBYNAME, "gethostbyname"),

MSNET_IMPORT(OS_GETHOSTNAME, "gethostname"),
MSNET_IMPORT(OS_GETPEERNAME, "getpeername"),
MSNET_IMPORT(OS_GETSOCKNAME, "getsockname"),
MSNET_IMPORT(OS_GETSOCKOPT, "getsockopt"),
MSNET_IMPORT(OS_INET_ADDR, "inet_addr"),
MSNET_IMPORT(OS_IOCTLSOCKET, "ioctlsocket"),
MSNET_IMPORT(OS_LISTEN, "listen"),

MSNET_IMPORT(OS_RECV, "recv"),
MSNET_IMPORT(OS_RECVFROM, "recvfrom"),
MSNET_IMPORT(OS_SELECT, "select"),

MSNET_IMPORT(OS_SEND, "send"),
MSNET_IMPORT(OS_SENDTO, "sendto"),
MSNET_IMPORT(OS_SETHOSTNAME, "sethostname"),
MSNET_IMPORT(OS_SETSOCKOPT, "setsockopt"),
MSNET_IMPORT(OS_SHUTDOWN, "shutdown"),
MSNET_IMPORT(OS_SOCKET, "socket"),

MSNET_IMPORT(OS_INET_NTOA, "inet_ntoa")
